### ISSUE TITLE
Android Build crashes

### ISSUE THREAD

**Issue by Wuselwog** [Cyberselves/community#2]
I tried to build my app and run it on the Oculus Quest. After a short time, I think right after trying to connect to my robot, it crashes almost everytime. The version is not experiencing any issues when started on Windows. The log is showing a few different reports each time it crashes, I appended screenshots of one such log. No Animus Log or tombstone has been recorded for this run. 

I tried to reproduce this issue by building the example animus scene in an empty project, but it is not crashing in this case. Let me know if you need more information about this issue.

![CrashReport2_1](https://user-images.githubusercontent.com/30385654/105005577-ccc28a00-5a35-11eb-99f2-ed565bc99db4.png)
![CrashReport2_2](https://user-images.githubusercontent.com/30385654/105005580-cd5b2080-5a35-11eb-9863-e8a8bf489fe9.png)
![CrashReport2_3](https://user-images.githubusercontent.com/30385654/105005584-cdf3b700-5a35-11eb-9da3-83a81f1611b6.png)
![CrashReport2_4](https://user-images.githubusercontent.com/30385654/105005585-cdf3b700-5a35-11eb-9ce5-58850926f5e8.png)
![CrashReport2_5](https://user-images.githubusercontent.com/30385654/105005575-cc29f380-5a35-11eb-8225-fc88ce6639dc.png)

**Comment by dcam0050** [comment]
Hi there, this is quite a weird issue as I don't see Animus being referenced in the stack trace for the error. Can you try a version of your code without Animus just to check if it is the source of the issue?

**Comment by Wuselwog** [comment]
I tried it, and it did not crash without the Animus instances in the scene. I tested a lot of different scenes and realized that the Animus SDK works fine on it's own, but it leads to a crash in my main scene. The crash ocures when the AnimusClientManager is in the scene, the error source seems to be in the Start function. I can test further to pinpoint the error location better. I already noted two things that could cause the error: 
-  this message saying that I can't open the log: "/storage/emulated/0/android/data/com.Roboy.Teleport/files/AnimusClientLog-_android-arm_20-01-2021-11-05-13: no such file or directory" (AnimusClientManager, line 104)
- the app is not asking for permissions, although it should ask for permissions on android
However, commenting out both code parts does not solve the problem. This is weird because it means the error has to be in the first half, but the latter half is still executed as it is able to log the message (I guess the first part invokes something that is executed in the following frame).  Do you have an idea where the error could be based on these findings?

**Comment by dcam0050** [comment]
With respect to permissions it should be asking for permission to access audio apart from the permission to access files and media. I don't think a lack of access to files and media should cause a crash especially not in the startup phase.

I can see that all the permission requests are present already in the Start() function of AnimusClientManager.

Can you check the following player settings please:
Min API Level = 21
Target API Level = 28
Target Architectures = Armv7
Internet Access = require
Write Permission = External (SD Card)

If all else fails, could you provide us with a simplified failing example for us to replicate please?

**Comment by Wuselwog** [comment]
Thanks. I solved it by removing another package, which I assume to have conflicted with animus. 

Yes, the app should ask for the permissions in the start function, which was why I was confused that it did not ask for them in the build. The demo app asks after each reinstall, my own build just one time after changing the Write Permission to External. But I think it's still working after asking just once, so this shouldn't pose a problem.
